### ISSUE TITLE
FAQs.md should be separated from Readme.md

### ISSUE THREAD

**Issue by tuliplab** [tulip-lab/flip00#1]
It is great that there is now a file for FAQs. But it is better to separate it from readme.

In addition, please get familiar with markdown format, so that you can properly write bullet points, URL, and refer to images which should be put in a different subfolders.

**Comment by YukaZhou** [comment]
OK. I will re-upload a more complete FAQ markdown file.

**Comment by tuliplab** [comment]
This remains an open task, and please resolve it @YukaZhou
