### ISSUE TITLE
[flip00-latex]Precautions for vscode running latex template

### ISSUE THREAD

**Issue by wang-404** [tulip-lab/flip00#4]
When vscode is configured for compilation, select recipe:dvi- >ps > pdf run.If the directory is not updated automatically after running, you can delete pdf and compile again.

**Comment by wang-404** [comment]
For the configuration of latex related to vscode, please refer to: https://zhuanlan.zhihu.com/p/166523064

**Comment by wang-404** [comment]
When writing the slide, gitinfo is used to update the lower right corner automatically. Please refer to elder martial sister's blog: https://kaezhou.tulip.academy/2020/09/28/gitinfo-configuration/

**Comment by 1024ytt** [comment]
When inserting an image, remember to convert the image format to EPS format, and the size of the image should not be too large, otherwise the insertion failure will occur.
